name: Build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-bun@v1
      - name: Lint
        run: bun lint
      - name: Check formatting
        run: bun fmt:check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-bun@v1
      - name: Test
        run: bun run test
  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: mskelton/setup-bun@v1
      - name: Build
        run: bun run build
      - name: Release
        run: bun semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
